#
# Makefile for toolchain
#
tch-highfive:
	@echo "=== BUILD Toolchain BEGIN ==="
	@BINUTILS_GDB_0233_INSTALL=$(DIR_DADAO_INSTALL) make -s binutils-gdb-0233-highfive
	@GCC_0902_INSTALL=$(DIR_DADAO_INSTALL) make -s gcc-0902-highfive
	@echo "=== BUILD Toolchain DONE! ==="

include DADAO-tch/Makefile.binutils-gdb
include DADAO-tch/Makefile.gcc
