#
# Makefile for tests
#
include $(DIR_DADAO_TOP)/DADAO-tests/common.mk

TESTS_BENCHMARKS_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/benchmarks/
TESTS_BENCHMARKS_BUILD		:= $(DIR_DADAO_TOP)/__tests/benchmarks/

TESTS_BOOTROM_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/bootrom/
TESTS_BOOTROM_BUILD		:= $(DIR_DADAO_TOP)/__tests/bootrom/

TESTS_DEJAGNU_INSTALL		:= $(DIR_DADAO_TOP)/__tests/dejagnu

TESTS_ISA_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/isa
TESTS_ISA_BUILD			:= $(DIR_DADAO_TOP)/__tests/isa

TESTS_SIMPLE_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/simple
TESTS_SIMPLE_BUILD		:= $(DIR_DADAO_TOP)/__tests/simple
TESTS_SIMPLE_INSN		?= insn-simple
TESTS_SIMPLE_HELLOWORLD		?= helloworld
#EXTRA_GCC_FLAGS		+= -fdump-tree-all -fdump-ipa-all -fdump-rtl-all

tests-benchmarks-highfive:
	@rm -fr $(TESTS_BENCHMARKS_BUILD)
	@mkdir $(TESTS_BENCHMARKS_BUILD)
	@ln -s $(TESTS_BENCHMARKS_SOURCE)/Makefile $(TESTS_BENCHMARKS_BUILD)/Makefile
	@make -s src_dir=$(TESTS_BENCHMARKS_SOURCE) -C $(TESTS_BENCHMARKS_BUILD)

tests-bootrom-highfive:
	@rm -fr $(TESTS_BOOTROM_BUILD)
	@mkdir -p $(TESTS_BOOTROM_BUILD)
	@cp $(TESTS_BOOTROM_SOURCE)/* $(TESTS_BOOTROM_BUILD)
	@make -s src_dir=$(TESTS_BOOTROM_SOURCE) -C $(TESTS_BOOTROM_BUILD)

tests-dejagnu-highfive:
	@rm -rf $(TESTS_DEJAGNU_INSTALL)
	@mkdir -p $(TESTS_DEJAGNU_INSTALL)/usr/bin
	@mkdir -p $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/baseboards
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/bin/ /usr/bin/runtest
	@ln -s $(DIR_DADAO_INSTALL)/bin/qemu-dadao $(TESTS_DEJAGNU_INSTALL)/usr/bin/dadao-unknown-elf-run
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/			\
		/usr/share/dejagnu/*.c						\
		/usr/share/dejagnu/*.exp					\
		/usr/share/dejagnu/libexec					\
		/usr/share/dejagnu/config
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/baseboards/	\
		/usr/share/dejagnu/baseboards/basic-sim.exp			\
		$(DIR_DADAO_TOP)/DADAO-tests/dejagnu/qemu-dadao.exp

tests-isa-bare-highfive:
	@rm -fr $(TESTS_ISA_BUILD)
	@mkdir -p $(TESTS_ISA_BUILD)
	@ln -s $(TESTS_ISA_SOURCE)/Makefile $(TESTS_ISA_BUILD)/Makefile
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) dduii-bare
	#@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) run-qemu

tests-isa-qemu-highfive:
	@rm -fr $(TESTS_ISA_BUILD)
	@mkdir -p $(TESTS_ISA_BUILD)
	@ln -s $(TESTS_ISA_SOURCE)/Makefile $(TESTS_ISA_BUILD)/Makefile
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) dduii-qemu
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) run-qemu

tests-simple-elf-highfive:
	@rm -fr $(TESTS_SIMPLE_BUILD)
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	@cd $(TESTS_SIMPLE_BUILD) ;										\
		$(DADAO_ELF_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S -o $(TESTS_SIMPLE_INSN).o ;	\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;			\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump
	@cd $(TESTS_SIMPLE_BUILD) ;										\
		$(DADAO_ELF_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_HELLOWORLD).c				\
			-save-temps										\
			-o $(TESTS_SIMPLE_HELLOWORLD) ;								\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_HELLOWORLD).o > $(TESTS_SIMPLE_HELLOWORLD).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_HELLOWORLD).o > $(TESTS_SIMPLE_HELLOWORLD).o.dump ;	\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_HELLOWORLD) > $(TESTS_SIMPLE_HELLOWORLD).elf ;		\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_HELLOWORLD) > $(TESTS_SIMPLE_HELLOWORLD).dump
	@$(DADAO_QEMU_USER) -singlestep -strace									\
		-D $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_HELLOWORLD).qemulog					\
		$(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_HELLOWORLD)

tests-simple-gnu-highfive:
	@rm -fr $(TESTS_SIMPLE_BUILD)
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	@cd $(TESTS_SIMPLE_BUILD) ;										\
		$(DADAO_GNU_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S					\
			-o $(TESTS_SIMPLE_INSN).o ;								\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;			\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump
	@cd $(TESTS_SIMPLE_BUILD) ;										\
		$(DADAO_GNU_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_HELLOWORLD).c				\
			-save-temps										\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crti.o				\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crtn.o				\
			-nostdlib -lgcc										\
			-B$(DIR_DADAO_BUILD)/gcc-$(VER_GCC)/gcc/						\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/bin/						\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/lib/						\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/include					\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/sys-include				\
			-o $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_HELLOWORLD) ;					\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_HELLOWORLD).o > $(TESTS_SIMPLE_HELLOWORLD).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_HELLOWORLD).o > $(TESTS_SIMPLE_HELLOWORLD).o.dump ;	\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_HELLOWORLD) > $(TESTS_SIMPLE_HELLOWORLD).elf ;		\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_HELLOWORLD) > $(TESTS_SIMPLE_HELLOWORLD).dump

