#
# Makefile for tests
#
include $(DIR_DADAO_TOP)/DADAO-tests/common.mk

TESTS_BOOTROM_SOURCE	:= $(DIR_DADAO_TOP)/DADAO-tests/bootrom/
TESTS_BOOTROM_BUILD	:= $(DIR_DADAO_TOP)/__tests/bootrom/

tests-bootrom-highfive:
	@rm -fr $(TESTS_BOOTROM_BUILD)
	@mkdir $(TESTS_BOOTROM_BUILD)
	@cp $(TESTS_BOOTROM_SOURCE)/* $(TESTS_BOOTROM_BUILD)
	@make -s src_dir=$(TESTS_BOOTROM_SOURCE) -C $(TESTS_BOOTROM_BUILD)

TESTS_DEJAGNU_INSTALL		:= $(DIR_DADAO_TOP)/__tests/dejagnu

tests-dejagnu-init:
	@rm -rf $(TESTS_DEJAGNU_INSTALL)
	@mkdir -p $(TESTS_DEJAGNU_INSTALL)/usr/bin
	@mkdir -p $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/baseboards
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/bin/ /usr/bin/runtest
	@ln -s $(DIR_DADAO_INSTALL)/bin/qemu-dadao $(TESTS_DEJAGNU_INSTALL)/usr/bin/dadao-unknown-elf-run
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/			\
		/usr/share/dejagnu/*.c						\
		/usr/share/dejagnu/*.exp					\
		/usr/share/dejagnu/libexec					\
		/usr/share/dejagnu/config
	@ln -s -t $(TESTS_DEJAGNU_INSTALL)/usr/share/dejagnu/baseboards/	\
		/usr/share/dejagnu/baseboards/basic-sim.exp			\
		$(DIR_DADAO_TOP)/DADAO-tests/dejagnu/qemu-dadao.exp

TESTS_ISA_SOURCE	:= $(DIR_DADAO_TOP)/DADAO-tests/isa
TESTS_ISA_BUILD		:= $(DIR_DADAO_TOP)/__tests/isa

tests-isa-clean:
	@rm -fr $(TESTS_ISA_BUILD)

tests-isa-source:
	@test -d $(TESTS_ISA_BUILD) || mkdir -p $(TESTS_ISA_BUILD)
	@ln -s $(TESTS_ISA_SOURCE)/Makefile $(TESTS_ISA_BUILD)/Makefile

tests-isa-bare-build:
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) dduii-bare

tests-isa-qemu-build:
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) dduii-qemu

tests-isa-bare-run:
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) run-bare

tests-isa-qemu-run:
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) run-qemu

tests-isa-bare-highfive:
	@make -s tests-isa-clean
	@make -s tests-isa-source
	@make -s tests-isa-bare-build
	@make -s tests-isa-bare-run

tests-isa-qemu-highfive:
	@make -s tests-isa-clean
	@make -s tests-isa-source
	@make -s tests-isa-qemu-build
	@make -s tests-isa-qemu-run

TESTS_SIMPLE_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/simple
TESTS_SIMPLE_BUILD		:= $(DIR_DADAO_TOP)/__tests/simple

TESTS_SIMPLE_INSN		?= insn-simple

tests-simple-insn-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S			\
			-o $(TESTS_SIMPLE_INSN).o ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump

tests-simple-insn-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S			\
			-o $(TESTS_SIMPLE_INSN).o ;						\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump


TESTS_SIMPLE_MAIN		?= main-simple
#EXTRA_GCC_FLAGS		+= -fdump-tree-all -fdump-ipa-all -fdump-rtl-all

tests-simple-main-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_MAIN).c			\
			-save-temps								\
			-o $(TESTS_SIMPLE_MAIN) ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.dump ;\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).dump

tests-simple-main-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_MAIN).c			\
			-save-temps								\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crti.o		\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crtn.o		\
			-nostdlib -lgcc								\
			-B$(DIR_DADAO_BUILD)/gcc-$(VER_GCC)/gcc/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/bin/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/lib/				\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/include			\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/sys-include		\
			-o $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN) ;				\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.dump ;\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).dump

tests-simple-main-qemu:
	$(DADAO_QEMU_USER) -singlestep -strace							\
		-D $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN).qemulog				\
		$(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN)

TESTS_HELLOWORLD		?= helloworld

tests-simple-helloworld-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_HELLOWORLD).c			\
			-save-temps								\
			-o $(TESTS_HELLOWORLD) ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.dump ;	\
		$(DADAO_ELF_READELF) -a $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).elf ;		\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).dump

tests-simple-helloworld-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_HELLOWORLD).c			\
			-save-temps								\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crti.o		\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crtn.o		\
			-nostdlib -lgcc								\
			-B$(DIR_DADAO_BUILD)/gcc-$(VER_GCC)/gcc/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/bin/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/lib/				\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/include			\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/sys-include		\
			-o $(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD) ;				\
		$(DADAO_GNU_READELF) -a $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.dump ;	\
		$(DADAO_GNU_READELF) -a $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).elf ;		\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).dump

tests-simple-helloworld-qemu:
	$(DADAO_QEMU_USER) -singlestep -strace							\
		-D $(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD).qemulog				\
		$(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD)

tests-simple-clean:
	@rm -fr $(TESTS_SIMPLE_BUILD)

tests-simple-elf-highfive:
	@make -s tests-simple-clean
	@make -s tests-simple-insn-elf
	@make -s tests-simple-main-elf
	@make -s tests-simple-main-qemu
	@make -s tests-simple-helloworld-elf
	@make -s tests-simple-helloworld-qemu

tests-simple-gnu-highfive:
	@make -s tests-simple-clean
	@make -s tests-simple-insn-gnu
	@make -s tests-simple-main-gnu
	@make -s tests-simple-main-qemu
	@make -s tests-simple-helloworld-gnu
	@make -s tests-simple-helloworld-qemu
