#
# Makefile for simple test
#
TESTS_SIMPLE_SOURCE		:= $(DIR_DADAO_TOP)/DADAO-tests/simple
TESTS_SIMPLE_BUILD		:= $(DIR_DADAO_TOP)/__tests/simple

include $(DIR_DADAO_TOP)/DADAO-tests/Makefile.tests-rules

TESTS_SIMPLE_INSN		?= insn-simple

tests-simple-insn-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S			\
			-o $(TESTS_SIMPLE_INSN).o ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump

tests-simple-insn-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GAS) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_INSN).S			\
			-o $(TESTS_SIMPLE_INSN).o ;						\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_INSN).o > $(TESTS_SIMPLE_INSN).o.dump


TESTS_SIMPLE_MAIN		?= main-simple
#EXTRA_GCC_FLAGS		+= -fdump-tree-all -fdump-ipa-all -fdump-rtl-all

tests-simple-main-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_MAIN).c			\
			-save-temps								\
			-o $(TESTS_SIMPLE_MAIN) ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.dump ;\
		$(DADAO_ELF_READELF) -a $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).dump

tests-simple-main-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_SIMPLE_MAIN).c			\
			-save-temps								\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crti.o		\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crtn.o		\
			-nostdlib -lgcc								\
			-B$(DIR_DADAO_BUILD)/gcc-$(VER_GCC)/gcc/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/bin/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/lib/				\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/include			\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/sys-include		\
			-o $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN) ;				\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN).o > $(TESTS_SIMPLE_MAIN).o.dump ;\
		$(DADAO_GNU_READELF) -a $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_SIMPLE_MAIN) > $(TESTS_SIMPLE_MAIN).dump

tests-simple-main-qemu:
	$(DADAO_QEMU_USER) -singlestep -strace							\
		-D $(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN).qemulog				\
		$(TESTS_SIMPLE_BUILD)/$(TESTS_SIMPLE_MAIN)

TESTS_HELLOWORLD		?= helloworld

tests-simple-helloworld-elf:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_ELF_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_HELLOWORLD).c			\
			-save-temps								\
			-o $(TESTS_HELLOWORLD) ;						\
		$(DADAO_ELF_READELF) -a $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.elf ;	\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.dump ;	\
		$(DADAO_ELF_READELF) -a $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).elf ;		\
		$(DADAO_ELF_OBJDUMP) -lDS $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).dump

tests-simple-helloworld-gnu:
	@test -d $(TESTS_SIMPLE_BUILD) || mkdir -p $(TESTS_SIMPLE_BUILD)
	cd $(TESTS_SIMPLE_BUILD) ;								\
		$(DADAO_GNU_GCC) $(TESTS_SIMPLE_SOURCE)/$(TESTS_HELLOWORLD).c			\
			-save-temps								\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crti.o		\
			$(DIR_DADAO_INSTALL)/lib/gcc/dadao-linux-gnu/10.3.0/crtn.o		\
			-nostdlib -lgcc								\
			-B$(DIR_DADAO_BUILD)/gcc-$(VER_GCC)/gcc/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/bin/				\
			-B$(DIR_DADAO_INSTALL)/dadao-linux-gnu/lib/				\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/include			\
			-isystem $(DIR_DADAO_INSTALL)/dadao-linux-gnu/sys-include		\
			-o $(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD) ;				\
		$(DADAO_GNU_READELF) -a $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.elf ;	\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_HELLOWORLD).o > $(TESTS_HELLOWORLD).o.dump ;	\
		$(DADAO_GNU_READELF) -a $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).elf ;		\
		$(DADAO_GNU_OBJDUMP) -lDS $(TESTS_HELLOWORLD) > $(TESTS_HELLOWORLD).dump

tests-simple-helloworld-qemu:
	$(DADAO_QEMU_USER) -singlestep -strace							\
		-D $(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD).qemulog				\
		$(TESTS_SIMPLE_BUILD)/$(TESTS_HELLOWORLD)

tests-simple-clean:
	@rm -fr $(TESTS_SIMPLE_BUILD)

tests-simple-elf-highfive:
	@make -s tests-simple-clean
	@make -s tests-simple-insn-elf
	@make -s tests-simple-main-elf
	@make -s tests-simple-main-qemu
	@make -s tests-simple-helloworld-elf
	@make -s tests-simple-helloworld-qemu

tests-simple-gnu-highfive:
	@make -s tests-simple-clean
	@make -s tests-simple-insn-gnu
	@make -s tests-simple-main-gnu
	@make -s tests-simple-main-qemu
	@make -s tests-simple-helloworld-gnu
	@make -s tests-simple-helloworld-qemu
