#
# Makefile for isa
#
TESTS_ISA_SOURCE	:= $(DIR_DADAO_TOP)/DADAO-tests/isa
TESTS_ISA_BUILD		:= $(DIR_DADAO_TOP)/__tests/isa

tests-isa-clean:
	@rm -fr $(TESTS_ISA_BUILD)

tests-isa-source:
	@test -d $(TESTS_ISA_BUILD) || mkdir -p $(TESTS_ISA_BUILD)
	@ln -s $(TESTS_ISA_SOURCE)/Makefile $(TESTS_ISA_BUILD)/Makefile

tests-isa-build:
	@make src_dir=$(TESTS_ISA_SOURCE) -C $(TESTS_ISA_BUILD) dduii

tests-isa-highfive:
	@make -s tests-isa-clean
	@make -s tests-isa-source
	@make -s tests-isa-build
