
generic-y += atomic.h
generic-y += bitops.h
generic-y += bug.h
generic-y += cmpxchg.h
generic-y += current.h
generic-y += div64.h
generic-y += irqflags.h
generic-y += linkage.h
generic-y += mmiowb.h
generic-y += mmu.h
generic-y += percpu.h
generic-y += preempt.h
generic-y += shmparam.h
generic-y += string.h
generic-y += timex.h
generic-y += topology.h
