#
# Makefile for coremark
#
DDB_COREMARK_ORIGIN	:= $(DIR_GIT_ORIGIN)/coremark.git
DDB_COREMARK_BUILD	:= $(DDB_DST_DIR)/coremark

bench-coremark-source:
	# Remove old coremark source dir ...
	@rm -fr $(DDB_COREMARK_BUILD)
	# Clone official repo
	@git clone -q $(DDB_COREMARK_ORIGIN) -- $(DDB_COREMARK_BUILD)

bench-coremark-build:
	@cd $(DDB_COREMARK_BUILD);					\
		PORT_DIR=linux						\
		CC=$(DDB_ELF_GCC)					\
		XCFLAGS="-static"					\
		NO_LIBRT=true						\
		make compile
